/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public interface siglib_wrapConstants {
  public final static int SIGLIB_SWIG_SWITCH = siglib_wrapJNI.SIGLIB_SWIG_SWITCH_get();
  public final static int SIGLIB = siglib_wrapJNI.SIGLIB_get();
  public final static double SIGLIB_VERSION = siglib_wrapJNI.SIGLIB_VERSION_get();
  public final static int SIGLIB_ENABLE_DEBUG_LOGGING = siglib_wrapJNI.SIGLIB_ENABLE_DEBUG_LOGGING_get();
  public final static int SIGLIB_FIX_DATA_SHORT = siglib_wrapJNI.SIGLIB_FIX_DATA_SHORT_get();
  public final static int SIGLIB_DATA_SHORT = siglib_wrapJNI.SIGLIB_DATA_SHORT_get();
  public final static int SIGLIB_DATA_LONG = siglib_wrapJNI.SIGLIB_DATA_LONG_get();
  public final static int SIGLIB_DATA_FLOAT = siglib_wrapJNI.SIGLIB_DATA_FLOAT_get();
  public final static int SIGLIB_INDEX_SHORT = siglib_wrapJNI.SIGLIB_INDEX_SHORT_get();
  public final static int SIGLIB_ARRAYS_ALIGNED = siglib_wrapJNI.SIGLIB_ARRAYS_ALIGNED_get();
  public final static int SIGLIB_FILE_IO_SUPPORTED = siglib_wrapJNI.SIGLIB_FILE_IO_SUPPORTED_get();
  public final static int SIGLIB_CONSOLE_IO_SUPPORTED = siglib_wrapJNI.SIGLIB_CONSOLE_IO_SUPPORTED_get();
  public final static int RAND_MAX = siglib_wrapJNI.RAND_MAX_get();
  public final static double SIGLIB_MINUS_ONE_HUNDRED = siglib_wrapJNI.SIGLIB_MINUS_ONE_HUNDRED_get();
  public final static double SIGLIB_MINUS_TEN = siglib_wrapJNI.SIGLIB_MINUS_TEN_get();
  public final static double SIGLIB_MINUS_TWO = siglib_wrapJNI.SIGLIB_MINUS_TWO_get();
  public final static double SIGLIB_MINUS_ONE = siglib_wrapJNI.SIGLIB_MINUS_ONE_get();
  public final static double SIGLIB_MINUS_HALF = siglib_wrapJNI.SIGLIB_MINUS_HALF_get();
  public final static double SIGLIB_ZERO = siglib_wrapJNI.SIGLIB_ZERO_get();
  public final static double SIGLIB_QUARTER = siglib_wrapJNI.SIGLIB_QUARTER_get();
  public final static double SIGLIB_THIRD = siglib_wrapJNI.SIGLIB_THIRD_get();
  public final static double SIGLIB_HALF = siglib_wrapJNI.SIGLIB_HALF_get();
  public final static double SIGLIB_ONE = siglib_wrapJNI.SIGLIB_ONE_get();
  public final static double SIGLIB_ONE_AND_HALF = siglib_wrapJNI.SIGLIB_ONE_AND_HALF_get();
  public final static double SIGLIB_TWO = siglib_wrapJNI.SIGLIB_TWO_get();
  public final static double SIGLIB_THREE = siglib_wrapJNI.SIGLIB_THREE_get();
  public final static double SIGLIB_FOUR = siglib_wrapJNI.SIGLIB_FOUR_get();
  public final static double SIGLIB_FIVE = siglib_wrapJNI.SIGLIB_FIVE_get();
  public final static double SIGLIB_SIX = siglib_wrapJNI.SIGLIB_SIX_get();
  public final static double SIGLIB_SEVEN = siglib_wrapJNI.SIGLIB_SEVEN_get();
  public final static double SIGLIB_EIGHT = siglib_wrapJNI.SIGLIB_EIGHT_get();
  public final static double SIGLIB_NINE = siglib_wrapJNI.SIGLIB_NINE_get();
  public final static double SIGLIB_TEN = siglib_wrapJNI.SIGLIB_TEN_get();
  public final static double SIGLIB_SIXTEEN = siglib_wrapJNI.SIGLIB_SIXTEEN_get();
  public final static double SIGLIB_TWENTY = siglib_wrapJNI.SIGLIB_TWENTY_get();
  public final static double SIGLIB_FIFTY = siglib_wrapJNI.SIGLIB_FIFTY_get();
  public final static double SIGLIB_SIXTY_FOUR = siglib_wrapJNI.SIGLIB_SIXTY_FOUR_get();
  public final static double SIGLIB_ONE_HUNDRED = siglib_wrapJNI.SIGLIB_ONE_HUNDRED_get();
  public final static double SIGLIB_TWO_HUNDRED = siglib_wrapJNI.SIGLIB_TWO_HUNDRED_get();
  public final static double SIGLIB_THREE_SIXTY = siglib_wrapJNI.SIGLIB_THREE_SIXTY_get();
  public final static double SIGLIB_PI = siglib_wrapJNI.SIGLIB_PI_get();
  public final static double SIGLIB_TWO_PI = siglib_wrapJNI.SIGLIB_TWO_PI_get();
  public final static double SIGLIB_HALF_PI = siglib_wrapJNI.SIGLIB_HALF_PI_get();
  public final static double SIGLIB_QUARTER_PI = siglib_wrapJNI.SIGLIB_QUARTER_PI_get();
  public final static double SIGLIB_FOUR_PI = siglib_wrapJNI.SIGLIB_FOUR_PI_get();
  public final static double SIGLIB_INV_PI = siglib_wrapJNI.SIGLIB_INV_PI_get();
  public final static double SIGLIB_INV_TWO_PI = siglib_wrapJNI.SIGLIB_INV_TWO_PI_get();
  public final static double SIGLIB_SQRT_PI = siglib_wrapJNI.SIGLIB_SQRT_PI_get();
  public final static double SIGLIB_PI_SQUARED = siglib_wrapJNI.SIGLIB_PI_SQUARED_get();
  public final static double SIGLIB_INV_EIGHT = siglib_wrapJNI.SIGLIB_INV_EIGHT_get();
  public final static double SIGLIB_INV_SIXTEEN = siglib_wrapJNI.SIGLIB_INV_SIXTEEN_get();
  public final static double SIGLIB_SQRT_TWO = siglib_wrapJNI.SIGLIB_SQRT_TWO_get();
  public final static double SIGLIB_INV_SQRT_TWO = siglib_wrapJNI.SIGLIB_INV_SQRT_TWO_get();
  public final static double SIGLIB_INV_SQRT_TWO_PI = siglib_wrapJNI.SIGLIB_INV_SQRT_TWO_PI_get();
  public final static double SIGLIB_SQRT_HALF_LN2 = siglib_wrapJNI.SIGLIB_SQRT_HALF_LN2_get();
  public final static double SIGLIB_LN2 = siglib_wrapJNI.SIGLIB_LN2_get();
  public final static double SIGLIB_THREE_SIXTY_OVER_TWO_PI = siglib_wrapJNI.SIGLIB_THREE_SIXTY_OVER_TWO_PI_get();
  public final static double SIGLIB_TWO_PI_OVER_THREE_SIXTY = siglib_wrapJNI.SIGLIB_TWO_PI_OVER_THREE_SIXTY_get();
  public final static double SIGLIB_INV_LOG10_OF_2 = siglib_wrapJNI.SIGLIB_INV_LOG10_OF_2_get();
  public final static double SIGLIB_DEGREES_TO_RADIANS = siglib_wrapJNI.SIGLIB_DEGREES_TO_RADIANS_get();
  public final static double SIGLIB_RADIANS_TO_DEGREES = siglib_wrapJNI.SIGLIB_RADIANS_TO_DEGREES_get();
}
