/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLArbitraryFFT_t {
  public final static SLArbitraryFFT_t SIGLIB_ARB_FFT_DO_CZT = new SLArbitraryFFT_t("SIGLIB_ARB_FFT_DO_CZT");
  public final static SLArbitraryFFT_t SIGLIB_ARB_FFT_DO_FFT = new SLArbitraryFFT_t("SIGLIB_ARB_FFT_DO_FFT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLArbitraryFFT_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLArbitraryFFT_t.class + " with value " + swigValue);
  }

  private SLArbitraryFFT_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLArbitraryFFT_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLArbitraryFFT_t(String swigName, SLArbitraryFFT_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLArbitraryFFT_t[] swigValues = { SIGLIB_ARB_FFT_DO_CZT, SIGLIB_ARB_FFT_DO_FFT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

