/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public class SLComplexPolar16_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SLComplexPolar16_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SLComplexPolar16_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        siglib_wrapJNI.delete_SLComplexPolar16_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMagn(short value) {
    siglib_wrapJNI.SLComplexPolar16_s_magn_set(swigCPtr, this, value);
  }

  public short getMagn() {
    return siglib_wrapJNI.SLComplexPolar16_s_magn_get(swigCPtr, this);
  }

  public void setAngle(short value) {
    siglib_wrapJNI.SLComplexPolar16_s_angle_set(swigCPtr, this, value);
  }

  public short getAngle() {
    return siglib_wrapJNI.SLComplexPolar16_s_angle_get(swigCPtr, this);
  }

  public SLComplexPolar16_s() {
    this(siglib_wrapJNI.new_SLComplexPolar16_s(), true);
  }

}
