/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLCompareType_t {
  public final static SLCompareType_t SIGLIB_NOT_EQUAL = new SLCompareType_t("SIGLIB_NOT_EQUAL");
  public final static SLCompareType_t SIGLIB_EQUAL = new SLCompareType_t("SIGLIB_EQUAL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLCompareType_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLCompareType_t.class + " with value " + swigValue);
  }

  private SLCompareType_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLCompareType_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLCompareType_t(String swigName, SLCompareType_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLCompareType_t[] swigValues = { SIGLIB_NOT_EQUAL, SIGLIB_EQUAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

