/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLCostasLoopFeedbackMode_t {
  public final static SLCostasLoopFeedbackMode_t SIGLIB_COSTAS_LOOP_MULTIPLY_LOOP = new SLCostasLoopFeedbackMode_t("SIGLIB_COSTAS_LOOP_MULTIPLY_LOOP");
  public final static SLCostasLoopFeedbackMode_t SIGLIB_COSTAS_LOOP_POLARITY_LOOP = new SLCostasLoopFeedbackMode_t("SIGLIB_COSTAS_LOOP_POLARITY_LOOP");
  public final static SLCostasLoopFeedbackMode_t SIGLIB_COSTAS_LOOP_HARD_LIMITED_LOOP = new SLCostasLoopFeedbackMode_t("SIGLIB_COSTAS_LOOP_HARD_LIMITED_LOOP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLCostasLoopFeedbackMode_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLCostasLoopFeedbackMode_t.class + " with value " + swigValue);
  }

  private SLCostasLoopFeedbackMode_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLCostasLoopFeedbackMode_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLCostasLoopFeedbackMode_t(String swigName, SLCostasLoopFeedbackMode_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLCostasLoopFeedbackMode_t[] swigValues = { SIGLIB_COSTAS_LOOP_MULTIPLY_LOOP, SIGLIB_COSTAS_LOOP_POLARITY_LOOP, SIGLIB_COSTAS_LOOP_HARD_LIMITED_LOOP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

