/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLELGTriggerTiming_t {
  public final static SLELGTriggerTiming_t SIGLIB_ELG_TRIGGER_START = new SLELGTriggerTiming_t("SIGLIB_ELG_TRIGGER_START");
  public final static SLELGTriggerTiming_t SIGLIB_ELG_TRIGGER_MIDDLE = new SLELGTriggerTiming_t("SIGLIB_ELG_TRIGGER_MIDDLE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLELGTriggerTiming_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLELGTriggerTiming_t.class + " with value " + swigValue);
  }

  private SLELGTriggerTiming_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLELGTriggerTiming_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLELGTriggerTiming_t(String swigName, SLELGTriggerTiming_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLELGTriggerTiming_t[] swigValues = { SIGLIB_ELG_TRIGGER_START, SIGLIB_ELG_TRIGGER_MIDDLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

