/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLFindType_t {
  public final static SLFindType_t SIGLIB_FIND_GREATER_THAN_ZERO = new SLFindType_t("SIGLIB_FIND_GREATER_THAN_ZERO");
  public final static SLFindType_t SIGLIB_FIND_GREATER_THAN_OR_EQUAL_TO_ZERO = new SLFindType_t("SIGLIB_FIND_GREATER_THAN_OR_EQUAL_TO_ZERO");
  public final static SLFindType_t SIGLIB_FIND_EQUAL_TO_ZERO = new SLFindType_t("SIGLIB_FIND_EQUAL_TO_ZERO");
  public final static SLFindType_t SIGLIB_FIND_LESS_THAN_ZERO = new SLFindType_t("SIGLIB_FIND_LESS_THAN_ZERO");
  public final static SLFindType_t SIGLIB_FIND_LESS_THAN_OR_EQUAL_TO_ZERO = new SLFindType_t("SIGLIB_FIND_LESS_THAN_OR_EQUAL_TO_ZERO");
  public final static SLFindType_t SIGLIB_FIND_NOT_EQUAL_TO_ZERO = new SLFindType_t("SIGLIB_FIND_NOT_EQUAL_TO_ZERO");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLFindType_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLFindType_t.class + " with value " + swigValue);
  }

  private SLFindType_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLFindType_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLFindType_t(String swigName, SLFindType_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLFindType_t[] swigValues = { SIGLIB_FIND_GREATER_THAN_ZERO, SIGLIB_FIND_GREATER_THAN_OR_EQUAL_TO_ZERO, SIGLIB_FIND_EQUAL_TO_ZERO, SIGLIB_FIND_LESS_THAN_ZERO, SIGLIB_FIND_LESS_THAN_OR_EQUAL_TO_ZERO, SIGLIB_FIND_NOT_EQUAL_TO_ZERO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

