/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLIIRNormalizedCoeffs_t {
  public final static SLIIRNormalizedCoeffs_t SIGLIB_BUTTERWORTH_IIR_NORM_COEFFS = new SLIIRNormalizedCoeffs_t("SIGLIB_BUTTERWORTH_IIR_NORM_COEFFS");
  public final static SLIIRNormalizedCoeffs_t SIGLIB_BESSEL_IIR_NORM_COEFFS = new SLIIRNormalizedCoeffs_t("SIGLIB_BESSEL_IIR_NORM_COEFFS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLIIRNormalizedCoeffs_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLIIRNormalizedCoeffs_t.class + " with value " + swigValue);
  }

  private SLIIRNormalizedCoeffs_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLIIRNormalizedCoeffs_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLIIRNormalizedCoeffs_t(String swigName, SLIIRNormalizedCoeffs_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLIIRNormalizedCoeffs_t[] swigValues = { SIGLIB_BUTTERWORTH_IIR_NORM_COEFFS, SIGLIB_BESSEL_IIR_NORM_COEFFS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

