/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLLevelCrossingMode_t {
  public final static SLLevelCrossingMode_t SIGLIB_POSITIVE_LEVEL_CROSS = new SLLevelCrossingMode_t("SIGLIB_POSITIVE_LEVEL_CROSS");
  public final static SLLevelCrossingMode_t SIGLIB_NEGATIVE_LEVEL_CROSS = new SLLevelCrossingMode_t("SIGLIB_NEGATIVE_LEVEL_CROSS");
  public final static SLLevelCrossingMode_t SIGLIB_ALL_LEVEL_CROSS = new SLLevelCrossingMode_t("SIGLIB_ALL_LEVEL_CROSS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLLevelCrossingMode_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLLevelCrossingMode_t.class + " with value " + swigValue);
  }

  private SLLevelCrossingMode_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLLevelCrossingMode_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLLevelCrossingMode_t(String swigName, SLLevelCrossingMode_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLLevelCrossingMode_t[] swigValues = { SIGLIB_POSITIVE_LEVEL_CROSS, SIGLIB_NEGATIVE_LEVEL_CROSS, SIGLIB_ALL_LEVEL_CROSS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

