/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public class SLMicrophone16_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SLMicrophone16_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SLMicrophone16_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        siglib_wrapJNI.delete_SLMicrophone16_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXPos(short value) {
    siglib_wrapJNI.SLMicrophone16_s_xPos_set(swigCPtr, this, value);
  }

  public short getXPos() {
    return siglib_wrapJNI.SLMicrophone16_s_xPos_get(swigCPtr, this);
  }

  public void setYPos(short value) {
    siglib_wrapJNI.SLMicrophone16_s_yPos_set(swigCPtr, this, value);
  }

  public short getYPos() {
    return siglib_wrapJNI.SLMicrophone16_s_yPos_get(swigCPtr, this);
  }

  public void setDelay(short value) {
    siglib_wrapJNI.SLMicrophone16_s_delay_set(swigCPtr, this, value);
  }

  public short getDelay() {
    return siglib_wrapJNI.SLMicrophone16_s_delay_get(swigCPtr, this);
  }

  public void setGain(short value) {
    siglib_wrapJNI.SLMicrophone16_s_gain_set(swigCPtr, this, value);
  }

  public short getGain() {
    return siglib_wrapJNI.SLMicrophone16_s_gain_get(swigCPtr, this);
  }

  public SLMicrophone16_s() {
    this(siglib_wrapJNI.new_SLMicrophone16_s(), true);
  }

}
