/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLParity_t {
  public final static SLParity_t SIGLIB_NO_PARITY = new SLParity_t("SIGLIB_NO_PARITY");
  public final static SLParity_t SIGLIB_EVEN_PARITY = new SLParity_t("SIGLIB_EVEN_PARITY");
  public final static SLParity_t SIGLIB_ODD_PARITY = new SLParity_t("SIGLIB_ODD_PARITY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLParity_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLParity_t.class + " with value " + swigValue);
  }

  private SLParity_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLParity_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLParity_t(String swigName, SLParity_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLParity_t[] swigValues = { SIGLIB_NO_PARITY, SIGLIB_EVEN_PARITY, SIGLIB_ODD_PARITY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

