/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLSignalFillMode_t {
  public final static SLSignalFillMode_t SIGLIB_FILL = new SLSignalFillMode_t("SIGLIB_FILL");
  public final static SLSignalFillMode_t SIGLIB_ADD = new SLSignalFillMode_t("SIGLIB_ADD");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLSignalFillMode_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLSignalFillMode_t.class + " with value " + swigValue);
  }

  private SLSignalFillMode_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLSignalFillMode_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLSignalFillMode_t(String swigName, SLSignalFillMode_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLSignalFillMode_t[] swigValues = { SIGLIB_FILL, SIGLIB_ADD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

