/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLSignalCoherenceType_t {
  public final static SLSignalCoherenceType_t SIGLIB_SIGNAL_COHERENT = new SLSignalCoherenceType_t("SIGLIB_SIGNAL_COHERENT");
  public final static SLSignalCoherenceType_t SIGLIB_SIGNAL_INCOHERENT = new SLSignalCoherenceType_t("SIGLIB_SIGNAL_INCOHERENT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLSignalCoherenceType_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLSignalCoherenceType_t.class + " with value " + swigValue);
  }

  private SLSignalCoherenceType_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLSignalCoherenceType_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLSignalCoherenceType_t(String swigName, SLSignalCoherenceType_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLSignalCoherenceType_t[] swigValues = { SIGLIB_SIGNAL_COHERENT, SIGLIB_SIGNAL_INCOHERENT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

