/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLSignalSign_t {
  public final static SLSignalSign_t SIGLIB_SIGNED_DATA = new SLSignalSign_t("SIGLIB_SIGNED_DATA");
  public final static SLSignalSign_t SIGLIB_UNSIGNED_DATA = new SLSignalSign_t("SIGLIB_UNSIGNED_DATA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLSignalSign_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLSignalSign_t.class + " with value " + swigValue);
  }

  private SLSignalSign_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLSignalSign_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLSignalSign_t(String swigName, SLSignalSign_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLSignalSign_t[] swigValues = { SIGLIB_SIGNED_DATA, SIGLIB_UNSIGNED_DATA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

