/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package siglib_wrap;

public final class SLThresholdMode_t {
  public final static SLThresholdMode_t SIGLIB_SINGLE_SIDED_THOLD = new SLThresholdMode_t("SIGLIB_SINGLE_SIDED_THOLD");
  public final static SLThresholdMode_t SIGLIB_DOUBLE_SIDED_THOLD = new SLThresholdMode_t("SIGLIB_DOUBLE_SIDED_THOLD");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SLThresholdMode_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SLThresholdMode_t.class + " with value " + swigValue);
  }

  private SLThresholdMode_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SLThresholdMode_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SLThresholdMode_t(String swigName, SLThresholdMode_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SLThresholdMode_t[] swigValues = { SIGLIB_SINGLE_SIDED_THOLD, SIGLIB_DOUBLE_SIDED_THOLD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

