@echo off

rem Batch file to build all the examples with GCC

call gb 180det
call gb adpcm
call gb agc
call gb all-pole
call gb am
call gb am2
call gb analytic
call gb arb-fft
call gb bilinear
call gb bitcount
call gb BPFilterLength
call gb bpsk
call gb bpsk8
call gb cepstrum
call gb ChanCode
call gb chirp_3d
call gb chirp-z
call gb chirp-z2
call gb clipping
call gb comb1
call gb comb2
call gb complex
call gb ComplexInterp
call gb compshft
call gb convolve
call gb ConvolveComplex
call gb CopyWithOverlap
call gb cornu_s
call gb correlate1
call gb correlate2
call gb correlate3
call gb costasl
call gb covar
call gb datatype
call gb dbpsk
call gb dct
call gb ddf
call gb debug
call gb decint
call gb deconv
call gb DeGlitch
call gb delay
call gb DeltMod1
call gb DeltMod2
call gb dfplusi
call gb dft
call gb dft_fft_scaling
call gb dotprod
call gb dtmf
call gb dtmf_gen
call gb dtmf_wav
call gb DTMFFilterLength
call gb duplicates
call gb echorev
call gb ELGate
call gb envelope
call gb envelope-hilbert
call gb envelope-hilbert-simple
call gb envelope-rms
call gb EuclideanDistance
call gb evm
call gb FDConCor
call gb FDFilt
call gb fdhilb
call gb fdinter2
call gb fdinterp
call gb fft
call gb fftbin
call gb fft_peak_interpolator
call gb fft_radix4
call gb fft_simple
call gb ffttone
call gb fifo
call gb Find
call gb fir1
call gb fir2
call gb fir3
call gb firComplex
call gb firWithStore
call gb firComplexWithStore
call gb firExtendedArray
call gb firComplexExtendedArray
call gb firadds
call gb firdesn
call gb firdesnw
call gb FracInt
call gb FreqMod1
call gb FreqMod2
call gb FreqModC
call gb fsk
call gb fskn
call gb fsktime
call gb GausFilt
call gb GoertzC
call gb GoertzD
call gb GoertzF
call gb harmonic
call gb hilbert
call gb histogram
call gb iir
call gb iir_coeff
call gb iir_mac
call gb iir2
call gb iir2PoleLPF
call gb IIR-Gain
call gb iirnotch
call gb iirshft1
call gb iirshft2
call gb iirshft3
call gb iirspln
call gb insert_extract
call gb IntDiff
call gb interleave
call gb interpolation
call gb inv_fir
call gb isquare
call gb kurtosis
call gb LeakyInt
call gb lin_dbm
call gb lms
call gb manchest
call gb MatchFil
call gb math
call gb matrix
call gb matrix2
call gb median
call gb microscan
call gb minmax
call gb minmaxs
call gb modcount
call gb modulate
call gb modulo
call gb movepeak
call gb mrate
call gb MSCoher
call gb msDelay
call gb multiplx
call gb NonCaus
call gb Offset
call gb OnePole
call gb OnePoleCutOffFrequency
call gb OnePoleTimeConstant
call gb OrdNIIR
call gb ovl_add
call gb parametricEqualizer
call gb PeakAveR
call gb pid
call gb PeakHold1
call gb PeakHold2
call gb pll
call gb pn9pn15
call gb polynom
call gb prbs
call gb preemp
call gb pre-warp
call gb psd
call gb pwm
call gb qam16
call gb qpsk
call gb qpsk2
call gb quantize
call gb rcf
call gb regress
call gb RemoveDC
call gb resamplc
call gb resample
call gb resize
call gb resonate
call gb rfft
call gb roots
call gb rotate
call gb round
call gb sc-ofdm
call gb sequence
call gb sgram
call gb shuffle
call gb sig_gen
call gb sig_gen_s
call gb sine_fft
call gb sinpower
call gb sinx_x
call gb sort
call gb spec_inv
call gb SpeedOfSoundInAir
call gb stats
call gb sortswap
call gb SyncAsyn
call gb TappedDelay
call gb TDShift
call gb trend
call gb trig
call gb trigger
call gb trigrev
call gb trigsel
call gb tworby1c
call gb VertexFinder
call gb vit-k3
call gb vit-v32
call gb wcdma
call gb weightvs
call gb WelchPSE
call gb window
call gb WordLen
call gb ZeroCross
call gb ZoomFFT
call gb ZoomFFTs
call gb zTransform
