#!/usr/bin/env bash

# Shell script to build all the examples using GCC

./gb.sh 180det
./gb.sh adpcm
./gb.sh agc
./gb.sh all-pole
./gb.sh am
./gb.sh am2
./gb.sh analytic
./gb.sh arb-fft
./gb.sh bilinear
./gb.sh bitcount
./gb.sh BPFilterLength
./gb.sh bpsk
./gb.sh bpsk8
./gb.sh cepstrum
./gb.sh ChanCode
./gb.sh chirp_3d
./gb.sh chirp-z
./gb.sh chirp-z2
./gb.sh clipping
./gb.sh comb1
./gb.sh comb2
./gb.sh complex
./gb.sh ComplexInterp
./gb.sh compshft
./gb.sh convolve
./gb.sh ConvolveComplex
./gb.sh CopyWithOverlap
./gb.sh cornu_s
./gb.sh correlate1
./gb.sh correlate2
./gb.sh correlate3
./gb.sh costasLoop
./gb.sh covar
./gb.sh datatype
./gb.sh dbpsk
./gb.sh dct
./gb.sh ddf
./gb.sh debug
./gb.sh decint
./gb.sh deconv
./gb.sh DeGlitch
./gb.sh delay
./gb.sh DeltMod1
./gb.sh DeltMod2
./gb.sh dfplusi
./gb.sh dft
./gb.sh dft_fft_scaling
./gb.sh differential_encoding
./gb.sh dotprod
./gb.sh dtmf
./gb.sh dtmf_gen
./gb.sh dtmf_wav
./gb.sh DTMFFilterLength
./gb.sh Duplicates
./gb.sh echorev
./gb.sh ELGate
./gb.sh envelope
./gb.sh envelope-hilbert
./gb.sh envelope-hilbert-simple
./gb.sh envelope-rms
./gb.sh EuclideanDistance
./gb.sh evm
./gb.sh FDConCor
./gb.sh FDFilt
./gb.sh fdhilb
./gb.sh fdinter2
./gb.sh fdinterp
./gb.sh fft
./gb.sh FFTBin
./gb.sh fft_peak_interpolator
./gb.sh fft_radix4
./gb.sh fft_simple
./gb.sh ffttone
./gb.sh fifo
./gb.sh Find
./gb.sh fir1
./gb.sh fir2
./gb.sh fir3
./gb.sh firComplex
./gb.sh firWithStore
./gb.sh firComplexWithStore
./gb.sh firExtendedArray
./gb.sh firComplexExtendedArray
./gb.sh firadds
./gb.sh firdesn
./gb.sh firdesnw
./gb.sh firnotch
./gb.sh FracInt
./gb.sh FreqMod1
./gb.sh FreqMod2
./gb.sh FreqModC
./gb.sh fsk
./gb.sh fskn
./gb.sh fsktime
./gb.sh GausFilt
./gb.sh GoertzC
./gb.sh GoertzD
./gb.sh GoertzF
./gb.sh harmonic
./gb.sh hilbert
./gb.sh histogram
./gb.sh iir
./gb.sh iir_coeff
./gb.sh iir_mac
./gb.sh iir2
./gb.sh iir2PoleLPF
./gb.sh IIR-Gain
./gb.sh iirNonCausal
./gb.sh iirnotch
./gb.sh iirshft1
./gb.sh iirshft2
./gb.sh iirshft3
./gb.sh iirspln
./gb.sh insert_extract
./gb.sh IntDiff
./gb.sh interleave
./gb.sh interpolation
./gb.sh inv_fir
./gb.sh isquare
./gb.sh kurtosis
./gb.sh LeakyInt
./gb.sh lin_dbm
./gb.sh lms
./gb.sh manchest
./gb.sh MatchedFilter
./gb.sh math
./gb.sh matrix
./gb.sh matrix2
./gb.sh median
./gb.sh microscan
./gb.sh minmax
./gb.sh minmaxs
./gb.sh mixedFFT
./gb.sh modcount
./gb.sh modulate
./gb.sh modulo
./gb.sh movepeak
./gb.sh mrate
./gb.sh MSCoher
./gb.sh msDelay
./gb.sh multiplx
./gb.sh Offset
./gb.sh OnePole
./gb.sh OnePoleCutOffFrequency
./gb.sh OnePoleTimeConstant
./gb.sh OrdNIIR
./gb.sh ovl_add
./gb.sh parametricEqualizer
./gb.sh PeakAveR
./gb.sh pid
./gb.sh PeakHold1
./gb.sh PeakHold2
./gb.sh pll
./gb.sh pn9pn15
./gb.sh polynom
./gb.sh prbs
./gb.sh preemp
./gb.sh pre-warp
./gb.sh psd
./gb.sh PulseRemoval
./gb.sh pwm
./gb.sh qam16
./gb.sh qpsk
./gb.sh qpsk_CostasQam
./gb.sh quantize
./gb.sh rcf
./gb.sh regress
./gb.sh RemoveDC
./gb.sh resamplc
./gb.sh resample
./gb.sh resize
./gb.sh resonate
./gb.sh rfft
./gb.sh roots
./gb.sh rotate
./gb.sh round
./gb.sh sc-ofdm
./gb.sh sequence
./gb.sh shuffle
./gb.sh sig_gen
./gb.sh sig_gen_s
./gb.sh sine_fft
./gb.sh sinpower
./gb.sh sinx_x
./gb.sh sort
./gb.sh spec_inv
./gb.sh spectrogram
./gb.sh SpeedOfSoundInAir
./gb.sh stats
./gb.sh sortswap
./gb.sh SyncAsyn
./gb.sh TappedDelay
./gb.sh TDShift
./gb.sh trend
./gb.sh trig
./gb.sh trigger
./gb.sh trigrev
./gb.sh trigsel
./gb.sh tworby1c
./gb.sh VertexFinder
./gb.sh vit-k3
./gb.sh vit-v32
./gb.sh wcdma
./gb.sh weightvs
./gb.sh WelchPSE
./gb.sh window
./gb.sh WordLen
./gb.sh ZeroCross
./gb.sh ZoomFFT
./gb.sh ZoomFFTs
./gb.sh zTransform
