@echo off

rem Batch file to build all the examples using the free Microsoft Visual Studio compiler 64 bit

call mb 180det
call mb adpcm
call mb agc
call mb all-pole
call mb am
call mb am2
call mb analytic
call mb arb-fft
call mb bilinear
call mb bitcount
call mb BPFilterLength
call mb bpsk
call mb bpsk8
call mb cepstrum
call mb ChanCode
call mb chirp_3d
call mb chirp-z
call mb chirp-z2
call mb clipping
call mb comb1
call mb comb2
call mb complex
call mb ComplexInterp
call mb compshft
call mb convolve
call mb ConvolveComplex
call mb CopyWithOverlap
call mb cornu_s
call mb correlate1
call mb correlate2
call mb correlate3
call mb costasLoop
call mb covar
call mb datatype
call mb dbpsk
call mb dct
call mb ddf
call mb debug
call mb decint
call mb deconv
call mb DeGlitch
call mb delay
call mb DeltMod1
call mb DeltMod2
call mb dfplusi
call mb dft
call mb dft_fft_scaling
call mb dotprod
call mb dtmf
call mb dtmf_gen
call mb dtmf_wav
call mb DTMFFilterLength
call mb Duplicates
call mb echorev
call mb ELGate
call mb envelope
call mb envelope-hilbert
call mb envelope-hilbert-simple
call mb envelope-rms
call mb EuclideanDistance
call mb evm
call mb FDConCor
call mb FDFilt
call mb fdhilb
call mb fdinter2
call mb fdinterp
call mb fft
call mb FFTBin
call mb fft_peak_interpolator
call mb fft_radix4
call mb fft_simple
call mb ffttone
call mb fifo
call mb Find
call mb fir1
call mb fir2
call mb fir3
call mb firComplex
call mb firWithStore
call mb firComplexWithStore
call mb firExtendedArray
call mb firComplexExtendedArray
call mb firadds
call mb firdesn
call mb firdesnw
call mb firnotch
call mb FracInt
call mb FreqMod1
call mb FreqMod2
call mb FreqModC
call mb fsk
call mb fskn
call mb fsktime
call mb GausFilt
call mb GoertzC
call mb GoertzD
call mb GoertzF
call mb harmonic
call mb hilbert
call mb histogram
call mb iir
call mb iir_coeff
call mb iir_mac
call mb iir2
call mb iir2PoleLPF
call mb IIR-Gain
call mb iirNonCausal
call mb iirnotch
call mb iirshft1
call mb iirshft2
call mb iirshft3
call mb iirspln
call mb insert_extract
call mb IntDiff
call mb interleave
call mb interpolation
call mb inv_fir
call mb isquare
call mb kurtosis
call mb LeakyInt
call mb lin_dbm
call mb lms
call mb manchest
call mb MatchedFilter
call mb math
call mb matrix
call mb matrix2
call mb median
call mb microscan
call mb minmax
call mb minmaxs
call mb mixedFFT
call mb modcount
call mb modulate
call mb modulo
call mb movepeak
call mb mrate
call mb MSCoher
call mb msDelay
call mb multiplx
call mb Offset
call mb OnePole
call mb OnePoleCutOffFrequency
call mb OnePoleTimeConstant
call mb OrdNIIR
call mb ovl_add
call mb parametricEqualizer
call mb PeakAveR
call mb pid
call mb PeakHold1
call mb PeakHold2
call mb pll
call mb pn9pn15
call mb polynom
call mb prbs
call mb preemp
call mb pre-warp
call mb psd
call mb PulseRemoval
call mb pwm
call mb qam16
call mb qpsk
call mb qpsk2
call mb quantize
call mb rcf
call mb regress
call mb RemoveDC
call mb resamplc
call mb resample
call mb resize
call mb resonate
call mb rfft
call mb roots
call mb rotate
call mb round
call mb sc-ofdm
call mb sequence
call mb shuffle
call mb sig_gen
call mb sig_gen_s
call mb sine_fft
call mb sinpower
call mb sinx_x
call mb sort
call mb spec_inv
call mb spectrogram
call mb SpeedOfSoundInAir
call mb stats
call mb sortswap
call mb SyncAsyn
call mb TappedDelay
call mb TDShift
call mb trend
call mb trig
call mb trigger
call mb trigrev
call mb trigsel
call mb tworby1c
call mb VertexFinder
call mb vit-k3
call mb vit-v32
call mb wcdma
call mb weightvs
call mb WelchPSE
call mb window
call mb WordLen
call mb ZeroCross
call mb ZoomFFT
call mb ZoomFFTs
call mb zTransform
