@echo off

rem Batch file for generating .def file from library
rem Notes: This script requires libsiglib.a to be located in the siglib/src folder

REM functionList.txt is generated by the linux build scripts which can be executed under Windows Subsystem for Linux (WSL)
REM nm ../../src/libsiglib.a | grep " T " | cut -d " " -f 3 >> functionList.txt

if exist siglib.def (
 del siglib.def
)

if not exist functionList.txt (
  echo ERROR - functionList.txt DOES NOT exist - compile SigLib under Linux using remakelinux.sh in the src folder
)

cl DefGen.c

if exist DefGen.exe (
  DefGen
  del DefGen.exe
  del DefGen.obj
) ELSE (
  echo ERROR - DefGen.exe not generated
)

if exist siglib.def (
  copy siglib.def ..\..\src /Y
  echo siglib.def file generated
) ELSE (
  echo ERROR - siglib.def file NOT generated
)

